### ISSUE TITLE
How do I compile this application?

### ISSUE THREAD

**Issue by infotek** [joeljfischer/TicTacToe#1]
I'm a total java noob... it took me a few minutes to figure this out.  I thought I would document it for the next noob who wants to compile this :)

Compile the .java files to .class files

`javac *.java`

Create the jar file:

`jar cvf tictactoe.jar *.class`

Execute the Class with main()

`java -cp tictactoe.jar Core`

To run it without having to tell java what class has main(), create the following file in the src directory:

MANIFEST.MF

with the following contents:
`
Main-Class: Core

`
It requires that extra newline

Create the jar file including the manifest:

`jar cmvf MANIFEST.MF tictactoe.jar *.class`

Execute it using the following command:

`java -jar tictactoe.jar`

**Comment by joeljfischer** [comment]
I added this to the README
